export const ACCOUNT_ACTION_TYPES = {
    FETCH_MENU_DATA: 'account/FETCH_MENU_DATA',
    UPDATA_SIDEBAR_MENU: 'account/UPDATA_SIDEBAR_MENU',
    UPDATE_IS_ADDNEW: 'account/UPDATE_IS_ADDNEW',
    UPDATE_KEY_BREAD: 'account/UPDATE_KEY_BREAD'
}